anguage: node_js

node_js:
   - node # will use latest node

branches:
  only:
    - master

before_script: # commands to run before the build step
   - npm install -g --silent @angular/cli@6.0.3
   - npm install -g firebase-tools@latest
  - npm install -g angular-cli-ghpages@latest
  - npm install --save-dev @angular/cli@6.0.3

script: # the build step
   - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive # firebase deploy after angular-cli build

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change
