#.travis.yml

language: node_js
node_js:
  - "7.5"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools@latest
  - npm install -g @angular/cli@latest
  - npm install --save-dev @angular/cli@latest

script:
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change